### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by navneet35371** [norberte/Feature-Based-Opinion-Mining#1]
Missing file grBoosting2.rds

**Comment by norberte** [comment]
Hi, good catch, I just noticed it. 
It could not be uploaded to GitHub, since the file is over 25 MB, even compressed. I will add a link to Dropbox, where it will be shared.

Also keep in mind that the current version of the whole system is not final. There are still small bugs that need to be fixed, plus installation instructions need to be written.

**Comment by navneet35371** [comment]
I was able to run most part. Faced issues with r file.

**Comment by norberte** [comment]
@navneet35371 Let me know what is the issue with the R file. The only things that I could think of is either you don't have one of the libraries installed, or depending on your version of R, the newest version reads in CSV files as a 'tibble' data structure, while the older versions don't have this 'tibble' data structure, so that could cause some issues when running the import csv r code. 

Another obvious issue could be if your CSV file does not have 301 columns (1st column is the feature_dependencyWord, then there are 300 dimensions of each vector, like dim1, dim2, dim3, dim4, ..., dim299, dim300).
